[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "0d0e676ceafcd12dcb2c43470fa564f2471d15be"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "5a7479ec03cb729a3cd51e9fc222d0bd478f54438d27d649a1091438649be4ca"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.x86_64-linux-gnu.tar.gz"
[[FFTW]]
arch = "armv7l"
git-tree-sha1 = "a55db49a8d7b673c2f8df8c67f6624b8e15ceac5"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "2b286cd2afcd68caf1dd64b1c9c333c124099c054c4903e4e3f68ad3d176f50a"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.arm-linux-musleabihf.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "d8e8fa3a42b8634cd38731dcbac05378db178ee7"
os = "macos"

    [[FFTW.download]]
    sha256 = "a1779b7c4ded4840544febb093bfb03da4b6ade37ac996979a48fd11d8c494a6"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.x86_64-apple-darwin14.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "ea93c95a01b34bce22a8c5311949942720bc6708"
os = "freebsd"

    [[FFTW.download]]
    sha256 = "26812b0ecda157a674856f1f671a5faef4bc9133a904fc1dca36bb32bcd6fad5"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.x86_64-unknown-freebsd11.1.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "14f132f1e0e1528e538dc5d0b4829e8ed4a5d1b1"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "aa5e90cfc15a532b7cd6a1fa9ea79a6015c1d4044cf2c2f3d927523b2e8e5f56"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.i686-linux-gnu.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "50bc29dfa8ea7f33e0493274bbfd74e86947e3b7"
os = "windows"

    [[FFTW.download]]
    sha256 = "5b70660701b6466e0cbd3dd7f4fb741e2098110114cac8386f1c8dcd7b9c1b7f"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.i686-w64-mingw32.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "1d4f993a1195a9492ca15a0b6b73ff36a4f192b0"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "0d0ef98bbf1ff1955414dab22ef11a3163994baf3ffcfe9e8e9ac14dd141fda8"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.i686-linux-musl.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "202de6f913074aab5ec3b10aa49e66b48592136b"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "7d6400a4df54b671f301b80b9e79bee7875cfd4a78e519fa6dbfdd38b4ccfc28"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.aarch64-linux-musl.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "b76b2e02a7fc217db062af8f84877714c1d7febb"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "ca6ed03d45a1b4f054c32d884ab3a20f55bd20c166372a35ceefe91f2f10c94d"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.aarch64-linux-gnu.tar.gz"
[[FFTW]]
arch = "powerpc64le"
git-tree-sha1 = "6e377bde264c9007b4016529656fe184f144805d"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "6a3e1d1cc34b24b329a91d0907ae4b50e8088aa83648ed251967c4a72f7b5390"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.powerpc64le-linux-gnu.tar.gz"
[[FFTW]]
arch = "armv7l"
git-tree-sha1 = "424352f2a42ecd6512ee7510d9690a873853f5fd"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "3c3f630c265e1806422bfe0bb5beebfe401651bf5c08ff2dd160cc859d3faf0d"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.arm-linux-gnueabihf.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "c7a55f1876caf663d882da1ccbb79c3d95dfa2ed"
os = "windows"

    [[FFTW.download]]
    sha256 = "fdbb0002ff49458d9faec14488d01ff904ec003a0c937649972ba92dc72e9f04"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.x86_64-w64-mingw32.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "698f3488292b93f1afe1cf35d9c13deddd212209"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "8c7acde8c76726a14db64ffc41357fa8d1950ba992ef2aa34ac08c462f7708b7"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+2/FFTW.v3.3.9.x86_64-linux-musl.tar.gz"
